version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Qwerty123456'
      MYSQL_DATABASE: 'renthub_db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'Qwerty123456'
    volumes:
      - mysql_data:/var/lib/mysql

    ports:
      - "3306:3306"

volumes:
  mysql_data: