# Generated by Django 5.0.7 on 2024-09-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_status_alter_listing_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
