# Generated by Django 5.0.7 on 2024-09-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(choices=[('berlin', 'Berlin'), ('munich', 'Munich'), ('hamburg', 'Hamburg'), ('frankfurt', 'Frankfurt'), ('cologne', 'Cologne'), ('stuttgart', 'Stuttgart'), ('düsseldorf', 'Düsseldorf'), ('leipzig', 'Leipzig'), ('dortmund', 'Dortmund'), ('dresden', 'Dresden'), ('hannover', 'Hannover'), ('bremen', 'Bremen'), ('nuremberg', 'Nuremberg'), ('essen', 'Essen'), ('duisburg', 'Duisburg'), ('bochum', 'Bochum'), ('wuppertal', 'Wuppertal'), ('bielefeld', 'Bielefeld'), ('bonn', 'Bonn'), ('mannheim', 'Mannheim'), ('karlsruhe', 'Karlsruhe'), ('augsburg', 'Augsburg'), ('wiesbaden', 'Wiesbaden'), ('münster', 'Münster'), ('gelsenkirchen', 'Gelsenkirchen'), ('aachen', 'Aachen'), ('braunschweig', 'Braunschweig'), ('chemnitz', 'Chemnitz'), ('kiel', 'Kiel'), ('magdeburg', 'Magdeburg'), ('freiburg', 'Freiburg'), ('lübeck', 'Lübeck'), ('rostock', 'Rostock'), ('potsdam', 'Potsdam'), ('oberhausen', 'Oberhausen'), ('mainz', 'Mainz'), ('erfurt', 'Erfurt'), ('halle', 'Halle'), ('hagen', 'Hagen'), ('darmstadt', 'Darmstadt'), ('heilbronn', 'Heilbronn'), ('kassel', 'Kassel'), ('mönchengladbach', 'Mönchengladbach'), ('saarbrücken', 'Saarbrücken'), ('regensburg', 'Regensburg')], max_length=255),
        ),
    ]
